service: betrayal-clojure
image: tkindy/betrayal-clojure

servers:
  web:
    - 69.164.220.122

proxy:
  ssl: true
  host: betrayal-beta.tylerkindy.com
  healthcheck:
    path: /up

registry:
  username: tkindy
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  dockerfile: Dockerfile.clojure

env:
  clear:
    DB_HOST: betrayal-db
    DB_NAME: betrayal
    DB_USER: betrayal
  secret:
    - DB_PASSWORD:POSTGRES_PASSWORD
